### ISSUE TITLE
How to get stream size without processing stream?

### ISSUE THREAD

**Issue by tomekit** [talesbarreto/uri_content#6]
Firstly, thank you for this great library. I've relied previously on: https://pub.dev/packages/uri_to_file which has huge memory implication and leaves temporary files.

I am trying to switch to: `uri_content` library, I am sending files using PUT to the external server passing stream like this:
```dart
 
Map<String, String> headers = {};
headers['content-length'] = streamSize; // Where to get it from? 

final options = new Options(
    headers: headers
);
      
final httpResponse = await dio.put(url, data: stream, options: options)
```

however I have no idea how do I easily get the streamSize without prior stream processing.

Is it possible to obtain the stream size somehow?

**Comment by talesbarreto** [comment]
Hi @tomekit , nice to hear that somebody else is using `uri_content`. Thanks 😄 

I was reluctant to implement this functionality because it relies on metadata that may not be correct. I will make that clear in the documentation and hope for the best.

There you go https://github.com/talesbarreto/uri_content/pull/7
